In [12]:
from ultralytics import YOLO
import cv2
import cvzone
import math
import time

# mempredik file video 
cap = cv2.VideoCapture(r"D:\Belajar FR\Youtube_2\video\cars.mp4")

model = YOLO("yolo11s.pt")

classNames = ["person", "bicycle", "car", "motorbike", "aeroplane", "bus", "train", "truck", "boat",
              "traffic light", "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat",
              "dog", "horse", "sheep", "cow", "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella",
              "handbag", "tie", "suitcase", "frisbee", "skis", "snowboard", "sports ball", "kite", "baseball bat",
              "baseball glove", "skateboard", "surfboard", "tennis racket", "bottle", "wine glass", "cup",
              "fork", "knife", "spoon", "bowl", "banana", "apple", "sandwich", "orange", "broccoli",
              "carrot", "hot dog", "pizza", "donut", "cake", "chair", "sofa", "pottedplant", "bed",
              "diningtable", "toilet", "tvmonitor", "laptop", "mouse", "remote", "keyboard", "cell phone",
              "microwave", "oven", "toaster", "sink", "refrigerator", "book", "clock", "vase", "scissors",
              "teddy bear", "hair drier", "toothbrush"
              ]

prev_frame_time = 0
new_frame_time = 0

# mengggunakan cvzone karena sudah terintegrasi dengan opencv dan sintaxnya mudah
while True:
    new_frame_time = time.time()
    success, img = cap.read()
    results = model(img, stream=True)
    for r in results:
        boxes = r.boxes
        for box in boxes:
            # Bounding Box
            x1, y1, x2, y2 = box.xyxy[0]
            x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2)
            # cv2.rectangle(img,(x1,y1),(x2,y2),(255,0,255),3)
            w, h = x2 - x1, y2 - y1            
            # Confidence
            conf = math.ceil((box.conf[0] * 100)) / 100
            # Class Name
            cls = int(box.cls[0])

            currentClass = classNames[cls]

            if currentClass == "car" or currentClass == "motorbike" or currentClass == "bus" or currentClass == "truck"\
                and conf > 0.3:
                cvzone.putTextRect(img, f'{classNames[cls]} {conf}', (max(0, x1), max(35, y1)), 
                               scale=1, thickness=1, offset=3)
                cvzone.cornerRect(img, (x1, y1, w, h), l=15, t=1)
 
    cv2.imshow("image", img)
    if cv2.waitKey(1) & 0xFF == ord('q'): 
        break

    fps = 1 / (new_frame_time - prev_frame_time)
    prev_frame_time = new_frame_time
    print(f"fps:{fps}")

cap.release()
cv2.destroyAllWindows()


0: 384x640 15 cars, 1 traffic light, 99.4ms
Speed: 3.4ms preprocess, 99.4ms inference, 4.6ms postprocess per image at shape (1, 3, 384, 640)
fps:5.661742974403403e-10

0: 384x640 13 cars, 94.5ms
Speed: 5.6ms preprocess, 94.5ms inference, 5.8ms postprocess per image at shape (1, 3, 384, 640)
fps:0.8439853100052901

0: 384x640 11 cars, 1 truck, 1 traffic light, 94.0ms
Speed: 4.6ms preprocess, 94.0ms inference, 4.7ms postprocess per image at shape (1, 3, 384, 640)
fps:7.511033829436319

0: 384x640 11 cars, 96.3ms
Speed: 4.8ms preprocess, 96.3ms inference, 3.1ms postprocess per image at shape (1, 3, 384, 640)
fps:7.522942954253993

0: 384x640 11 cars, 94.4ms
Speed: 3.2ms preprocess, 94.4ms inference, 3.4ms postprocess per image at shape (1, 3, 384, 640)
fps:7.825515226371231

0: 384x640 12 cars, 93.8ms
Speed: 3.9ms preprocess, 93.8ms inference, 3.4ms postprocess per image at shape (1, 3, 384, 640)
fps:7.982035062077995

0: 384x640 12 cars, 94.5ms
Speed: 4.0ms preprocess, 94.5ms inference,

In [2]:
from ultralytics import YOLO
import cv2
import cvzone
import math
import time

# mempredik file video 
cap = cv2.VideoCapture(r"D:\Belajar FR\Youtube_2\video\cars.mp4")

model = YOLO("yolo11s.pt")

classNames = ["person", "bicycle", "car", "motorbike", "aeroplane", "bus", "train", "truck", "boat",
              "traffic light", "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat",
              "dog", "horse", "sheep", "cow", "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella",
              "handbag", "tie", "suitcase", "frisbee", "skis", "snowboard", "sports ball", "kite", "baseball bat",
              "baseball glove", "skateboard", "surfboard", "tennis racket", "bottle", "wine glass", "cup",
              "fork", "knife", "spoon", "bowl", "banana", "apple", "sandwich", "orange", "broccoli",
              "carrot", "hot dog", "pizza", "donut", "cake", "chair", "sofa", "pottedplant", "bed",
              "diningtable", "toilet", "tvmonitor", "laptop", "mouse", "remote", "keyboard", "cell phone",
              "microwave", "oven", "toaster", "sink", "refrigerator", "book", "clock", "vase", "scissors",
              "teddy bear", "hair drier", "toothbrush"
              ]

prev_frame_time = 0
new_frame_time = 0

mask = cv2.imread(r"mask.png")

# mengggunakan cvzone karena sudah terintegrasi dengan opencv dan sintaxnya mudah
while True:
    new_frame_time = time.time()
    success, img = cap.read()
    imgRegion = cv2.bitwise_and(img, mask)
    results = model(img, stream=True)
    for r in results:
        boxes = r.boxes
        for box in boxes:
            # Bounding Box
            x1, y1, x2, y2 = box.xyxy[0]
            x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2)
            # cv2.rectangle(img,(x1,y1),(x2,y2),(255,0,255),3)
            w, h = x2 - x1, y2 - y1            
            # Confidence
            conf = math.ceil((box.conf[0] * 100)) / 100
            # Class Name
            cls = int(box.cls[0])

            currentClass = classNames[cls]

            if currentClass == "car" or currentClass == "motorbike" or currentClass == "bus" or currentClass == "truck"\
                and conf > 0.3:
                cvzone.putTextRect(img, f'{classNames[cls]} {conf}', (max(0, x1), max(35, y1)), 
                               scale=1, thickness=1, offset=3)
                cvzone.cornerRect(img, (x1, y1, w, h), l=15, t=1)
 
    cv2.imshow("image", img)
    cv2.imshow("imageRegion", imgRegion)
    if cv2.waitKey(1) & 0xFF == ord('q'): 
        break

    fps = 1 / (new_frame_time - prev_frame_time)
    prev_frame_time = new_frame_time
    print(f"fps:{fps}")

cap.release()
cv2.destroyAllWindows()


0: 384x640 15 cars, 1 traffic light, 108.6ms
Speed: 3.5ms preprocess, 108.6ms inference, 3.7ms postprocess per image at shape (1, 3, 384, 640)
fps:5.661738439584678e-10

0: 384x640 13 cars, 94.8ms
Speed: 4.7ms preprocess, 94.8ms inference, 4.1ms postprocess per image at shape (1, 3, 384, 640)
fps:0.8621690222141462

0: 384x640 11 cars, 1 truck, 1 traffic light, 94.0ms
Speed: 5.7ms preprocess, 94.0ms inference, 4.4ms postprocess per image at shape (1, 3, 384, 640)
fps:7.38879992671631

0: 384x640 11 cars, 93.7ms
Speed: 7.5ms preprocess, 93.7ms inference, 4.2ms postprocess per image at shape (1, 3, 384, 640)
fps:7.446267904189066

0: 384x640 11 cars, 93.4ms
Speed: 7.0ms preprocess, 93.4ms inference, 4.0ms postprocess per image at shape (1, 3, 384, 640)
fps:7.53631146392212

0: 384x640 12 cars, 94.2ms
Speed: 4.8ms preprocess, 94.2ms inference, 2.7ms postprocess per image at shape (1, 3, 384, 640)
fps:7.630613388445389

0: 384x640 12 cars, 93.1ms
Speed: 3.2ms preprocess, 93.1ms inference,

In [6]:
from ultralytics import YOLO
import cv2
import cvzone
import math
import time
from sort import *

# mempredik file video 
cap = cv2.VideoCapture(r"D:\Belajar FR\Youtube_2\video\cars.mp4")

model = YOLO("yolo11s.pt")

classNames = ["person", "bicycle", "car", "motorbike", "aeroplane", "bus", "train", "truck", "boat",
              "traffic light", "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat",
              "dog", "horse", "sheep", "cow", "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella",
              "handbag", "tie", "suitcase", "frisbee", "skis", "snowboard", "sports ball", "kite", "baseball bat",
              "baseball glove", "skateboard", "surfboard", "tennis racket", "bottle", "wine glass", "cup",
              "fork", "knife", "spoon", "bowl", "banana", "apple", "sandwich", "orange", "broccoli",
              "carrot", "hot dog", "pizza", "donut", "cake", "chair", "sofa", "pottedplant", "bed",
              "diningtable", "toilet", "tvmonitor", "laptop", "mouse", "remote", "keyboard", "cell phone",
              "microwave", "oven", "toaster", "sink", "refrigerator", "book", "clock", "vase", "scissors",
              "teddy bear", "hair drier", "toothbrush"
              ]

prev_frame_time = 0
new_frame_time = 0

mask = cv2.imread(r"mask.png")

traker = Sort()

limit = [185, 400, 750, 400] # ini nilai dari x, y, width, height dari pembatas counter
counter = []

# mengggunakan cvzone karena sudah terintegrasi dengan opencv dan sintaxnya mudah
while True:
    new_frame_time = time.time()
    success, img = cap.read()
    imgRegion = cv2.bitwise_and(img, mask)
    results = model(imgRegion, stream=True)
    
    detection=np.empty((0, 5))

    for r in results:
        boxes = r.boxes
        for box in boxes:
            # Bounding Box
            x1, y1, x2, y2 = box.xyxy[0]
            x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2)
            # cv2.rectangle(img,(x1,y1),(x2,y2),(255,0,255),3)
            w, h = x2 - x1, y2 - y1            
            # Confidence
            conf = math.ceil((box.conf[0] * 100)) / 100
            # Class Name
            cls = int(box.cls[0])

            currentClass = classNames[cls]

            if currentClass == "car" or currentClass == "motorbike" or currentClass == "bus" or currentClass == "truck"\
                and conf > 0.3:
                # cvzone.putTextRect(img, f'{classNames[cls]} {conf}', (max(0, x1), max(35, y1)), 
                #                scale=1, thickness=1, offset=3)
                # cvzone.cornerRect(img, (x1, y1, w, h), l=15, t=1, rt=5)
                currentArray = np.array([x1, y1, x2, y2, conf])
                detection = np.vstack((detection, currentArray))
 

    resultTraker = traker.update(detection)
    cv2.line(img, (limit[0], limit[1]), (limit[2], limit[3]), (0, 0, 255), 5)

    for x in resultTraker:
        x1, y1, x2, y2, id = x
        x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2)
        print(x)

        w, h = x2 - x1, y2 - y1
        cvzone.cornerRect(img, (x1, y1, w, h), l=15, t=1, rt=5, colorR=(255, 0, 0))
        cvzone.putTextRect(img, f'{int(id)}', (max(0, x1), max(35, y1)), 
                               scale=2, thickness=3, offset=1)
        
        centerx, centery = x1 + w // 2, y1 + h // 2
        cv2.circle(img, (centerx, centery), 5, (255, 0, 255), cv2.FILLED)

        if limit[0] < centerx < limit[2] and limit[1] - 20 < centery < limit[3] + 20:
            if counter.count(id) == 0:
                counter.append(id)
                cv2.line(img, (limit[0], limit[1]), (limit[2], limit[3]), (0, 255, 0), 5)
    
    cvzone.putTextRect(img, f'Counter: {len(counter)}', (50, 100), 
                               scale=2, thickness=1, offset=20)



    cv2.imshow("image", img)
    # cv2.imshow("imageRegion", imgRegion)
    if cv2.waitKey(1) & 0xFF == ord('q'): 
        break

    fps = 1 / (new_frame_time - prev_frame_time)
    prev_frame_time = new_frame_time
    print(f"fps:{fps}")

cap.release()
cv2.destroyAllWindows()


0: 384x640 2 cars, 1 truck, 97.3ms
Speed: 3.2ms preprocess, 97.3ms inference, 2.9ms postprocess per image at shape (1, 3, 384, 640)
[        571         316         652         428          66]
[        378         348         495         456          65]
fps:5.661729819869354e-10

0: 384x640 2 cars, 1 truck, 95.5ms
Speed: 4.1ms preprocess, 95.5ms inference, 2.8ms postprocess per image at shape (1, 3, 384, 640)
[        570         321         648         436          67]
[     569.51      321.71      649.49      435.29          66]
[     373.72      351.26      493.28      462.74          65]
fps:1.4545283043731867

0: 384x640 2 cars, 1 truck, 95.6ms
Speed: 4.0ms preprocess, 95.6ms inference, 4.2ms postprocess per image at shape (1, 3, 384, 640)
[     553.47      353.56      631.54      478.43          67]
[     557.45      347.51      649.08      477.08          66]
[     351.15      368.03      480.68      489.86          65]
fps:7.722368389559172

0: 384x640 2 cars, 94.7ms
Speed: 

In [1]:
from ultralytics import YOLO
import cv2
import cvzone
import math
import time
import numpy as np
from sort import Sort


# -----------------------------
# Utilities
# -----------------------------
def load_mask(mask_path: str):
    """Load mask as 1-channel grayscale (recommended for ROI masking)."""
    mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
    if mask is None:
        raise FileNotFoundError(f"Mask tidak ditemukan: {mask_path}")
    return mask


def apply_mask(img, mask_gray):
    """Resize mask to match img and apply ROI mask."""
    mask_resized = cv2.resize(mask_gray, (img.shape[1], img.shape[0]))
    img_region = cv2.bitwise_and(img, img, mask=mask_resized)
    return img_region


def yolo_detections_to_sort(results, classNames, allowed_classes, conf_thres=0.3):
    """
    Convert YOLO results into SORT detections array:
    [[x1, y1, x2, y2, conf], ...]
    """
    detections = np.empty((0, 5), dtype=float)

    for r in results:
        for box in r.boxes:
            x1, y1, x2, y2 = map(int, box.xyxy[0])
            conf = float(box.conf[0])
            cls = int(box.cls[0])
            currentClass = classNames[cls]

            if (currentClass in allowed_classes) and (conf > conf_thres):
                currentArray = np.array([x1, y1, x2, y2, conf], dtype=float)
                detections = np.vstack((detections, currentArray))

    return detections


def draw_counting_line(img, line, color=(0, 0, 255), thickness=5):
    x1, y1, x2, y2 = line
    cv2.line(img, (x1, y1), (x2, y2), color, thickness)


def update_counter_and_draw(img, tracks, line, counter_ids, line_tolerance=20):
    """
    Draw tracked boxes + ids + center points.
    Count object if its center crosses the counting line area.
    """
    xL1, yL1, xL2, yL2 = line

    for t in tracks:
        x1, y1, x2, y2, track_id = t
        x1, y1, x2, y2 = map(int, [x1, y1, x2, y2])
        track_id = int(track_id)

        w, h = x2 - x1, y2 - y1
        cx, cy = x1 + w // 2, y1 + h // 2

        # Draw bbox + id + center
        cvzone.cornerRect(img, (x1, y1, w, h), l=15, t=1, rt=5, colorR=(255, 0, 0))
        cvzone.putTextRect(img, f"{track_id}", (max(0, x1), max(35, y1)),
                           scale=2, thickness=3, offset=1)
        cv2.circle(img, (cx, cy), 5, (255, 0, 255), cv2.FILLED)

        # Counting condition (line is horizontal here)
        # If center is within x-range and close to y of line
        if xL1 < cx < xL2 and (yL1 - line_tolerance) < cy < (yL2 + line_tolerance):
            if track_id not in counter_ids:
                counter_ids.add(track_id)
                draw_counting_line(img, line, color=(0, 255, 0), thickness=5)


def draw_fps(img, prev_time):
    """Return updated prev_time and draw FPS on frame."""
    now = time.time()
    fps = 1 / max(now - prev_time, 1e-6)
    cvzone.putTextRect(img, f"FPS: {int(fps)}", (20, 50), scale=1, thickness=2)
    return now


# -----------------------------
# Main
# -----------------------------
def main():
    video_path = r"D:\Belajar FR\Youtube_2\video\cars.mp4"
    mask_path = r"mask.png"
    model_path = "yolo11s.pt"

    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise FileNotFoundError(f"Video tidak bisa dibuka: {video_path}")

    model = YOLO(model_path)

    classNames = ["person", "bicycle", "car", "motorbike", "aeroplane", "bus", "train", "truck", "boat",
                  "traffic light", "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat",
                  "dog", "horse", "sheep", "cow", "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella",
                  "handbag", "tie", "suitcase", "frisbee", "skis", "snowboard", "sports ball", "kite", "baseball bat",
                  "baseball glove", "skateboard", "surfboard", "tennis racket", "bottle", "wine glass", "cup",
                  "fork", "knife", "spoon", "bowl", "banana", "apple", "sandwich", "orange", "broccoli",
                  "carrot", "hot dog", "pizza", "donut", "cake", "chair", "sofa", "pottedplant", "bed",
                  "diningtable", "toilet", "tvmonitor", "laptop", "mouse", "remote", "keyboard", "cell phone",
                  "microwave", "oven", "toaster", "sink", "refrigerator", "book", "clock", "vase", "scissors",
                  "teddy bear", "hair drier", "toothbrush"]

    allowed_classes = {"car", "motorbike", "bus", "truck"}
    conf_thres = 0.3

    mask_gray = load_mask(mask_path)
    tracker = Sort()

    # line format: [x1, y1, x2, y2]
    line = [185, 400, 750, 400]

    counter_ids = set()
    prev_time = time.time()

    while True:
        success, img = cap.read()
        if not success or img is None:
            print("Video selesai / frame tidak terbaca.")
            break

        # apply ROI mask
        imgRegion = apply_mask(img, mask_gray)

        # YOLO detection on region
        results = model(imgRegion, stream=True)

        # to SORT format
        detections = yolo_detections_to_sort(
            results, classNames, allowed_classes, conf_thres=conf_thres
        )

        # update tracker
        tracks = tracker.update(detections)

        # draw default line (red)
        draw_counting_line(img, line, color=(0, 0, 255), thickness=5)

        # draw tracks + counting
        update_counter_and_draw(img, tracks, line, counter_ids, line_tolerance=20)

        # draw counter
        cvzone.putTextRect(img, f"Counter: {len(counter_ids)}", (50, 100),
                           scale=2, thickness=1, offset=20)

        # fps
        prev_time = draw_fps(img, prev_time)

        cv2.imshow("image", img)
        # cv2.imshow("imageRegion", imgRegion)

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cap.release()
    cv2.destroyAllWindows()


if __name__ == "__main__":
    main()



0: 384x640 2 cars, 1 truck, 359.0ms
Speed: 204.3ms preprocess, 359.0ms inference, 186.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 cars, 1 truck, 97.2ms
Speed: 3.8ms preprocess, 97.2ms inference, 23.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 cars, 1 truck, 96.2ms
Speed: 3.3ms preprocess, 96.2ms inference, 2.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 cars, 94.4ms
Speed: 3.8ms preprocess, 94.4ms inference, 2.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 cars, 93.5ms
Speed: 3.8ms preprocess, 93.5ms inference, 3.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 cars, 94.8ms
Speed: 5.4ms preprocess, 94.8ms inference, 5.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 cars, 94.1ms
Speed: 5.1ms preprocess, 94.1ms inference, 4.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 cars, 93.2ms
Speed: 3.8ms preprocess, 93.2ms inference, 3.3ms postprocess per image 